"""
Draw Figure 1, the selective-prediction setting, as a vector schematic.

The figure is authored in millimetre coordinates at its printed size (183 mm,
double column) so that type sizes are true point sizes in the journal. The
only raster element is one real validation patch from the dataset, written by
scripts/figures/extract_fig1_patch.py on the machine that holds PathMNIST.
No part of the figure is generated by an image model.

Without the patch the script draws a grey placeholder so the layout can be
reviewed; --final refuses to build in that state, because a placeholder must
never reach the manuscript.

Usage:
    python scripts/figures/make_fig1.py            # draft, placeholder allowed
    python scripts/figures/make_fig1.py --final    # requires the real patch
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib import patheffects as pe
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Rectangle

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PATCH_PATH = PROJECT_ROOT / "scripts" / "figures" / "raw" / "fig1_patch_tum.png"
OUT_DIR = PROJECT_ROOT / "paper" / "latex" / "figures"

MM = 1 / 25.4
PT = 0.3528  # mm per typographic point, so font sizes below are true points

W, H = 183.0, 84.0
MID = 50.0  # centre line of the three routes; everything above the cohort band hangs off it

# Model colours follow the data figures (calibrate.py, plot_paper_figures.py):
# MedGemma red and the CNN blue. Route (i) covers both VLMs, so it takes a
# colour no single model uses, and the specialist queue is grey so it does not
# read as MedGemma.
VLM_PAIR, MEDGEMMA, CNN = "#8172B2", "#D65F5F", "#4878CF"
GREEN, GREY = "#009E73", "#666666"
INK = "#1A1A1A"
UM_PER_PX = 0.5  # NCT-CRC-HE-100K release: 224 x 224 px at 0.5 microns per pixel

FS_TITLE, FS_LABEL, FS_ANN = 7.5, 7.0, 6.0


def _box(ax, x, y, w, h, color, alpha=0.12, lw=0.8, dashed=False, rounded=True):
    style = "round,pad=0,rounding_size=1.6" if rounded else "square,pad=0"
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h, boxstyle=style, facecolor=color, alpha=alpha, edgecolor="none",
    ))
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h, boxstyle=style, facecolor="none", edgecolor=color, linewidth=lw,
        linestyle=(0, (3, 2)) if dashed else "solid",
    ))


def _text(ax, x, y, s, size=FS_LABEL, color=INK, weight="normal", ha="center", va="center",
          style="normal"):
    ax.text(x, y, s, fontsize=size, color=color, fontweight=weight, ha=ha, va=va,
            fontstyle=style, linespacing=1.15)


def _arrow(ax, p0, p1, color=GREY, lw=0.8):
    ax.add_patch(FancyArrowPatch(
        p0, p1, arrowstyle="-|>,head_length=1.6,head_width=0.9", mutation_scale=1,
        color=color, linewidth=lw, shrinkA=0, shrinkB=0,
    ))


def _row(ax, y, color, tag, model, model_sub, signal, signal_sub):
    h = 12.0
    _box(ax, 34, y - h / 2, 44, h, color)
    _text(ax, 36.5, y + 2.4, tag, FS_LABEL, color, "bold", ha="left")
    _text(ax, 43.5, y + 2.4, model, FS_LABEL, INK, "bold", ha="left")
    _text(ax, 36.5, y - 2.4, model_sub, FS_ANN, INK, ha="left")
    _box(ax, 86, y - h / 2, 42, h, color, alpha=0.20)
    _text(ax, 107, y + 2.4, signal, FS_LABEL, INK, "bold")
    _text(ax, 107, y - 2.4, signal_sub, FS_ANN, INK)
    _arrow(ax, (78, y), (86, y), color)
    _arrow(ax, (128, y), (137.0, MID + (y - MID) * 0.35), color)


def draw(final: bool) -> plt.Figure:
    have_patch = PATCH_PATH.exists()
    if final and not have_patch:
        sys.exit(f"--final needs the real patch at {PATCH_PATH}; run "
                 "scripts/figures/extract_fig1_patch.py on the data machine first.")

    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
        "pdf.fonttype": 42,
        "svg.fonttype": "none",
    })
    fig = plt.figure(figsize=(W * MM, H * MM))
    ax = fig.add_axes((0, 0, 1, 1))
    ax.set_xlim(0, W)
    ax.set_ylim(0, H)
    ax.set_aspect("equal")
    ax.axis("off")

    # Input patch. 24 mm is large enough to read tissue at print size.
    px, ps = 4.0, 24.0
    py = MID - ps / 2
    if have_patch:
        ax.imshow(mpimg.imread(PATCH_PATH), extent=(px, px + ps, py, py + ps),
                  interpolation="lanczos", zorder=2)
    else:
        ax.add_patch(Rectangle((px, py), ps, ps, facecolor="#D9D9D9", edgecolor="none"))
        _text(ax, px + ps / 2, py + ps / 2, "real patch\ninserted on\ndata machine",
              FS_ANN, GREY, style="italic")
    ax.add_patch(Rectangle((px, py), ps, ps, facecolor="none", edgecolor=INK, linewidth=0.6,
                           zorder=3))
    if have_patch:
        # 50 um scale bar; the patch spans 224 px, so 1 px is ps / 224 mm here.
        bar = 50.0 / UM_PER_PX * ps / 224.0
        halo = [pe.withStroke(linewidth=1.6, foreground="white")]
        x1 = px + ps - 1.6
        ax.plot([x1 - bar, x1], [py + 1.6, py + 1.6], color=INK, lw=1.4,
                solid_capstyle="butt", zorder=4, path_effects=halo)
        ax.text(x1 - bar / 2, py + 2.6, "50 µm", fontsize=FS_ANN, color=INK, ha="center",
                va="bottom", fontweight="bold", zorder=4, path_effects=halo)
    _text(ax, px + ps / 2, py - 3.2, "H&E patch", FS_LABEL, INK, "bold")
    _text(ax, px + ps / 2, py - 6.6, "224 × 224 px", FS_ANN)

    # Fan-out from the patch to the three routes.
    rows = (MID + 16.0, MID, MID - 16.0)
    ax.plot([px + ps, 31], [MID, MID], color=GREY, lw=0.8)
    ax.plot([31, 31], [rows[2], rows[0]], color=GREY, lw=0.8)
    for y in rows:
        _arrow(ax, (31, y), (34, y))

    # The object of evaluation, drawn as a container around the signal column.
    _box(ax, 83, MID - 23.5, 48, 52.5, GREY, alpha=0.05, lw=0.6, dashed=True)
    _text(ax, 107, MID + 25.8, "Evaluated: the confidence signal", FS_TITLE, INK, "bold")

    _row(ax, rows[0], VLM_PAIR, "(i)", "VLM, one prompt",
         "MedGemma-27b-it or Gemma-3-27b-it,\nzero-shot, prompt V3",
         "Label + verbalized confidence", "e.g. TUM, 95; also label-token\nprobability")
    _row(ax, rows[1], MEDGEMMA, "(ii)", "MedGemma, K = 5",
         "MedGemma-27b-it only,\nfive prompt variants",
         "Modal label + agreement", "e.g. 4 of 5 agree, score 0.80")
    _row(ax, rows[2], CNN, "(iii)", "ResNet-18",
         "supervised reference,\n64 px input",
         "Label + softmax confidence", "external cohort only")

    # Routing policy, drawn as the same rounded node as the stages before it.
    cx, cy, hw, hh = 146.0, MID, 9.0, 7.0
    _box(ax, cx - hw, cy - hh, 2 * hw, 2 * hh, INK, alpha=0.0, lw=0.8)
    _text(ax, cx, cy + 2.2, "Routing", FS_LABEL, INK, "bold")
    _text(ax, cx, cy - 2.2, "rank by signal", FS_ANN)

    _box(ax, 158, cy + 8.5, 24, 11, GREEN, alpha=0.15)
    _text(ax, 170, cy + 15.6, "Auto-confirmed", FS_LABEL, INK, "bold")
    _text(ax, 170, cy + 12.0, "highest-ranked 1 − b", FS_ANN)
    _box(ax, 158, cy - 19.5, 24, 11, GREY, alpha=0.15)
    _text(ax, 170, cy - 12.4, "Specialist queue", FS_LABEL, INK, "bold")
    _text(ax, 170, cy - 16.0, "lowest-ranked b", FS_ANN)
    _arrow(ax, (cx + 3.0, cy + hh), (158, cy + 14), GREEN)
    _arrow(ax, (cx + 3.0, cy - hh), (158, cy - 14), GREY)

    # Cohorts. The arrow carries the kind of shift, so the boxes need not.
    _box(ax, 4, 4, 80, 18, GREY, alpha=0.07, lw=0.6)
    _text(ax, 7, 18.4, "Source: NCT-CRC-HE-100K", FS_TITLE, INK, "bold", ha="left")
    _text(ax, 7, 12.6, "86 slides, NCT biobank Heidelberg and UMM Mannheim\n"
                       "validation split: 10,004 patches", FS_ANN, ha="left")
    _text(ax, 7, 7.0, "VLM prompt chosen on a 450-patch pilot from this split", FS_ANN,
          GREY, ha="left", style="italic")
    _box(ax, 101, 4, 80, 18, GREY, alpha=0.07, lw=0.6)
    _text(ax, 104, 18.4, "External: CRC-VAL-HE-7K", FS_TITLE, INK, "bold", ha="left")
    _text(ax, 104, 12.6, "25 slides from 50 DACHS patients, NCT Heidelberg\n"
                         "test split: 7,180 patches", FS_ANN, ha="left")
    _text(ax, 104, 7.0, "no model, prompt or setting chosen here", FS_ANN, GREY,
          ha="left", style="italic")
    _arrow(ax, (84, 13), (101, 13), INK, lw=0.8)
    _text(ax, 92.5, 15.6, "cohort shift", FS_ANN, INK)
    return fig


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--final", action="store_true",
                        help="refuse to build without the real patch")
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    fig = draw(args.final)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    pdf = args.out_dir / "fig1_pipeline.pdf"
    png = args.out_dir / "fig1_pipeline.png"
    fig.savefig(pdf)
    fig.savefig(png, dpi=600)
    plt.close(fig)
    print(f"Saved: {pdf}")
    print(f"Saved: {png}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
